first go at old ITs

diff --git a/.github/workflows/standard_its.yml b/.github/workflows/standard_its.yml
--- a/.github/workflows/standard_its.yml
+++ b/.github/workflows/standard_its.yml
@@ -17,6 +17,14 @@ name: Revised Integration Tests shared workflow
 on:
   workflow_call:
     inputs:
+      maven_projects:
+        description: 'Maven projects to test'
+        required: true
+        type: string
+      druid_use_default_value_for_null:
+        required: false
+        type: boolean
+        default: 'true'
       script:
         description: 'Which IT script to run'
         required: true
@@ -41,9 +49,10 @@ env:
   MAVEN_OPTS: -Xmx3000m
   JVM_RUNTIME: -Djvm.runtime=${{ inputs.runtime_jdk }}
   USE_INDEXER: ${{ inputs.use_indexer }}
+  DRUID_USE_DEFAULT_VALUE_FOR_NULL: ${{ inputs.druid_use_default_value_for_null }}
 
 jobs:
-  run-it:
+  run-processing-module-test:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout branch
@@ -54,11 +63,39 @@ jobs:
           distribution: 'zulu'
           java-version: ${{ inputs.compile_jdk }}
           cache: 'maven'
-      - name: Maven install
-        run: |
-           ./check_test_suite.py && exit 0 ||
-          echo 'Running Maven install...' &&
-          ${MVN} clean install -q -ff -pl '!distribution,!:druid-it-image,!:druid-it-cases' ${MAVEN_SKIP} ${MAVEN_SKIP_TESTS} -T1C &&
-          ${MVN} install -q -ff -pl 'distribution' ${MAVEN_SKIP} ${MAVEN_SKIP_TESTS}
       - name: Run IT
-        run: ${{ inputs.script }}
+        run: |
+          unset _JAVA_OPTIONS
+          # Set MAVEN_OPTS for Surefire launcher. Skip remoteresources to avoid intermittent connection timeouts when
+          # resolving the SIGAR dependency.
+          ${MVN} test -pl ${{ inputs.maven_projects }} ${MAVEN_SKIP} -Dremoteresources.skip=true -Ddruid.generic.useDefaultValueForNull=${{ inputs.druid_use_default_value_for_null }}
+          sh -c "dmesg | egrep -i '(oom|out of memory|kill process|killed).*' -C 1 || exit 0"
+          free -m
+          ${MVN} -pl ${MAVEN_PROJECTS} jacoco:report
+          if [[ "${GITHUB_REF_TYPE}" = "branch" ]]; then git remote set-branches --add origin ${GITHUB_REF_NAME} && git fetch; fi
+          all_files="$(git diff --name-only origin/${GITHUB_REF_NAME}...HEAD | grep "\.java$" || [[ $? == 1 ]])"
+          for f in ${all_files}; do echo $f; done  # for debugging
+          if [[ "${MAVEN_PROJECTS}" = \!* ]]; then
+          regex="${MAVEN_PROJECTS:1}";
+          regex="^${regex//,\!/\\|^}";
+          project_files="$(echo "${all_files}" | grep -v "${regex}" || [[ $? == 1 ]])";
+          else
+          regex="^${MAVEN_PROJECTS//,/\\|^}";
+          project_files="$(echo "${all_files}" | grep "${regex}" || [[ $? == 1 ]])";
+          fi
+        - for f in ${project_files}; do echo $f; done  # for debugging
+          if [ -n "${project_files}" ]; then
+          npm install @connectis/diff-test-coverage@1.5.3 && git diff origin/${GITHUB_REF_NAME}...HEAD -- ${project_files} | node_modules/.bin/diff-test-coverage \
+          --coverage "**/target/site/jacoco/jacoco.xml" \
+          --type jacoco \
+          --line-coverage 50 \
+          --branch-coverage 50 \
+          --function-coverage 0 \
+          --log-template "coverage-lines-complete" \
+          --log-template "coverage-files-complete" \
+          --log-template "totals-complete" \
+          --log-template "errors" \
+          -- || { printf "\n\n****FAILED****\nDiff code coverage check failed. To view coverage report, run 'mvn clean test jacoco:report' and open 'target/site/jacoco/index.html'\nFor more details on how to run code coverage locally, follow instructions here - https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md#running-code-coverage-locally\n\n" && false; }
+          fi
+          curl -o codecov.sh -s https://codecov.io/bash
+          bash codecov.sh -X gcov
